//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20F_0292_BCS_6E_Advanced_Programming_Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookstoreDBEntities : DbContext
    {
        public bookstoreDBEntities()
            : base("name=bookstoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addBook> addBooks { get; set; }
        public virtual DbSet<addUser> addUsers { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
